@startuml
'https://plantuml.com/class-diagram


Usuario "*"--Grupo
Usuario --"*"Grupo
Usuario --"*" Chat
Bot --"*" Grupo
Bot --"*" Comando
Chat --"*" Mensaje
Comando --"*"  iAccion
abstract class Individuo {
    tipo: String
    recibirMsj()
}
class Usuario implements Individuo{
    - nombre: String
    - nick: String
    - grupos: List<Grupo>
    - chats: List<Grupo>
    + salirDeGrupo(Grupo)
    + mandarMensaje(Mensaje)
}

class Grupo {
    - nombre: Grupo
    - participantes: Individuo
    - administrador: Usuario
    +agregarParticipante(Usuario usuario)
    +eliminarParticipante(Usuario usuario)
    +agregarAdministrador(Usuario usuario)

}
class Chat {
    Participantes: pueden ser usuarios comunes o bots
    Mensajes: List<Mensaje>
}

class Mensaje {
    emisor: Individuo
    receptor: List<Individuo>
    cuerpoMensaje: String
    adjunto: List<String>
    fechaHoraEnviado: DateTime
    fechaHoraRecibido: DateTime
    fechaHoraLeído: DateTime
}


class Bot implements Individuo{
    - Nombre
    - Comandos: List<Comando>
    + parsearAComando()
}

class Comando {
    - TextoComando: List<String>
    - Acciones: List<iAccion>
    + ejecutar(Mensaje)
}

interface iAccion {
    + ejecutar(parametros)
}
@enduml